version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - "nu12"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - "nu12"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - "nu12"