name: Release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  cd:
    name: Release
    uses: nu12/templates/.github/workflows/go-release.yml@main
    with:
      go-binary-name: 'az-dump'
      go-main: 'main.go'
      go-version: '1.23.0'
      release-linux-amd64: true
      release-win-amd64: true
      release-darwin-amd64: true
      release-darwin-arm64: true
      release-docker: true
      version: '${{ github.ref_name }}'
    secrets: inherit